language: node_js

node_js:
  - "10.15.3"

branches:
  only:
    - master

install:
  - npm ci
  - npm i -g codecov

script:
  - npm run build
  - npm run test

after_success:
  bash <(curl -s https://codecov.io/bash);

notifications:
  email: false
