export const clientUrls = {
  home: '/',
  login: '/login',
  passwordReset: '/reset-password/:token',
  analytics: '/analytics',
  vehicles: '/vehicles',
  reminders: '/reminders',
  remindersById: '/reminders/:id',
  map: '/map',
  mapWithId: '/map/:id',
  chat: '/chat',
  chatWithUserById: '/chat/:id',
  settings: '/settings',
  profile: '/profile',
};
